static_resources:
  listeners:
  - name: frontend_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: frontend_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend_services
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  weighted_clusters:
                    clusters:
                    - name: pinger_v1
                      weight: 95
                    - name: pinger_v2
                      weight: 5
          http_filters:
          - name: envoy.filters.http.router

  clusters:
  - name: pinger_v1
    connect_timeout: 5s
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: pinger_v1
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: pinger-v1
                port_value: 3000

  - name: pinger_v2
    connect_timeout: 5s
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: pinger_v2
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: pinger-v2
                port_value: 3000

admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901

