static_resources:
  listeners:
  - name: details_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: details_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: details_routes
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: details_app
          http_filters:
          - name: envoy.filters.http.router

  clusters:
  # ðŸ”¹ Details application (same pod)
  - name: details_app
    connect_timeout: 5s
    type: logical_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: details_app
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 4000

admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901

