# Sample reference for deployment yamls
# This need not be one file, can be split into 
# separate files.
# Command to deploy:
# kubectl apply -f <file/path> 
# Deployment file for frontend service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
  labels:
    app: frontend
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/stats/prometheus"
        prometheus.io/port: "9901"
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: localhost/frontend:v1
        env:
        - name: PINGER_BASE_URL
          value: "http://localhost:10000"
        - name: DETAILS_BASE_URL
          value: "http://localhost:10000"
        ports:
        - containerPort: 9000
        imagePullPolicy: IfNotPresent # else might try to pull images remotely always
     
      - name: envoy
        image: envoyproxy/envoy:v1.18-latest
        command: ["/bin/sh"]
        args: ["/etc/envoy/run-envoy.sh"]
        ports:
          - name: http
            containerPort: 10000
          - name: admin
            containerPort: 9901
        volumeMounts:
          - name: envoy-frontend-config
            mountPath: /etc/envoy
      volumes:
        - name: envoy-frontend-config
          configMap:
            name: envoy-frontend-config


---
# Service for frontend
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
    version: v1
  name: frontend-service
  namespace: default
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: frontend
  sessionAffinity: None
  type: ClusterIP
---
# Deployment for details service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: details
  namespace: default
  labels:
    app: details
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: details
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/stats/prometheus"
        prometheus.io/port: "9901"
      labels:
        app: details
    spec:
      containers:
      - name: details
        image: localhost/details:v1
        ports:
        - containerPort: 4000
        imagePullPolicy: IfNotPresent
      - name: envoy
        image: envoyproxy/envoy:v1.18-latest
        args:
          - "-c"
          - "/etc/envoy/envoy.yaml"
          - "--log-level"
          - "info"
        ports:
          - name: http
            containerPort: 10000
          - name: admin
            containerPort: 9901
        volumeMounts:
          - name: envoy-details-config
            mountPath: /etc/envoy
      volumes:
      - name: envoy-details-config
        configMap:
          name: envoy-details-config

---
# Service for details
apiVersion: v1
kind: Service
metadata:
  labels:
    app: details
    version: v1
  name: details-service
  namespace: default
spec:
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: details
  sessionAffinity: None
  type: ClusterIP
---
# Deployment for pinger app v1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinger-v1
  namespace: default
  labels:
    app: pinger
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pinger
      version: v1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/stats/prometheus"
        prometheus.io/port: "9901"
      labels:
        app: pinger
        version: v1
    spec:
      containers:
      - name: pinger
        image: localhost/pinger:v1
        ports:
        - containerPort: 3000
        imagePullPolicy: IfNotPresent
     

      - name: envoy
        image: envoyproxy/envoy:v1.18-latest
        args:
          - "-c"
          - "/etc/envoy/envoy.yaml"
          - "--log-level"
          - "info"
        ports:
          - name: http
            containerPort: 10000
          - name: admin
            containerPort: 9901
        volumeMounts:
          - name: envoy-pinger-config
            mountPath: /etc/envoy

      volumes:
      - name: envoy-pinger-config
        configMap:
          name: envoy-pinger-config   
---
# Service for pinger app v1
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pinger
    version: v1
  name: pinger-v1-service
  namespace: default
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: pinger
    version: v1
  sessionAffinity: None
  type: ClusterIP
---
# Deployment for pinger app v2
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinger-v2
  namespace: default
  labels:
    app: pinger
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pinger
      version: v2
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/stats/prometheus"
        prometheus.io/port: "9901"
      labels:
        app: pinger
        version: v2
    spec:
      containers:
      - name: pinger
        image: localhost/pinger:v2
        ports:
        - containerPort: 3000
        imagePullPolicy: IfNotPresent

      - name: envoy
        image: envoyproxy/envoy:v1.18-latest
        args:
          - "-c"
          - "/etc/envoy/envoy.yaml"
          - "--log-level"
          - "info"
        ports:
          - name: http
            containerPort: 10000
          - name: admin
            containerPort: 9901
        volumeMounts:
          - name: envoy-pinger-config
            mountPath: /etc/envoy

      volumes:
      - name: envoy-pinger-config
        configMap:
          name: envoy-pinger-config
---
# Service for ping app v2
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pinger
    version: v2
  name: pinger-v2-service
  namespace: default
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: pinger
    version: v2
  sessionAffinity: None
  type: ClusterIP
---
